drop table if exists ss_task;
drop table if exists ss_user;

create table ss_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table ss_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);


create table PMS_BD_GROUP(
	id bigint generated by default as identity,
	code varchar(64) not null unique,
	name varchar(255) not null,
	user_id bigint  ,
	description varchar(255),
	parent_id bigint  ,
	primary key (id)
);
create table PMS_BD_LEVEL(
	id bigint generated by default as identity,
	code varchar(64) not null unique,
	name varchar(255) not null,
	description varchar(255),
	user_id bigint  ,
	parent_id bigint  ,
	primary key (id)
);
create table PMS_BD_EMAIL(
	id bigint generated by default as identity,
	code varchar(64) not null unique,
	name varchar(255) not null,
	email varchar(255) not null,
	description varchar(255),
	user_id bigint  ,
	primary key (id)
);